name: Deploy

on:
  push:
    branches:
      - master
      
env:
  USERNAME: ${{ secrets.T800_USERNAME }}
  NUGET_API_KEY: ${{ secrets.T800_NUGET_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
    
      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '8.0.x'
      
      - name: Setup Nuget
        run: dotnet nuget add source --name Confirp --username $USERNAME --password "$NUGET_API_KEY" https://git.confirpdigital.com:55667/api/packages/Confirp/nuget/index.json --store-password-in-clear-text

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Debug --no-restore
      
      - name: Test
        run: dotnet test --no-restore --verbosity normal

      - name: Publish
        run: dotnet nuget push --source Confirp "**/*.nupkg" --api-key $NUGET_API_KEY --skip-duplicate
